
import type { GameState, Galaxy, Good, Planet, PlayerState } from './types';

export const UPGRADE_CONSTANTS = {
  CARGO: {
    PER_LEVEL: 5,
    BASE_COST: 500,
    COST_MULTIPLIER: 1.5,
    MAX_LEVEL: 10,
  },
  DURABILITY: {
    PER_LEVEL: 10,
    BASE_COST: 800,
    COST_MULTIPLIER: 1.8,
    MAX_LEVEL: 10,
  },
};

const GOODS: Good[] = [
  { id: 'water', name: 'Aqua Pura', basePrice: 20 },
  { id: 'food', name: 'Nutri-Paste', basePrice: 50 },
  { id: 'minerals', name: 'Xenon Crystals', basePrice: 150 },
  { id: 'tech', name: 'Quantum Chips', basePrice: 500 },
  { id: 'meds', name: 'Med-Kits', basePrice: 250 },
  { id: 'robots', name: 'Service Droids', basePrice: 800 },
  { id: 'luxuries', name: 'Jovian Silk', basePrice: 1200 },
  { id: 'gases', name: 'Helium-3 Isotopes', basePrice: 300 },
  { id: 'agri', name: 'Gen-Modified Seeds', basePrice: 80 },
  { id: 'info', name: 'Encrypted Data', basePrice: 600 },
  { id: 'parts', name: 'Ship Components', basePrice: 400 },
  { id: 'artifacts', name: 'Alien Artifacts', basePrice: 2000 },
];

const PLANETS: Planet[] = [
  {
    id: 'terra',
    name: 'Terra Prime',
    position: { x: 400, y: 300, z: 20 },
    taxRate: 0.05,
    description: "The bustling capital of the 'MakeMoney' galaxy, with a balanced economy and stable markets.",
    color: 'royalblue',
    market: [
      { goodId: 'water', buyPrice: 22, sellPrice: 18 },
      { goodId: 'food', buyPrice: 55, sellPrice: 45 },
      { goodId: 'minerals', buyPrice: 160, sellPrice: 140 },
      { goodId: 'tech', buyPrice: 480, sellPrice: 450 },
      { goodId: 'meds', buyPrice: 255, sellPrice: 240 },
      { goodId: 'robots', buyPrice: 810, sellPrice: 790 },
      { goodId: 'luxuries', buyPrice: 1250, sellPrice: 1150 },
      { goodId: 'gases', buyPrice: 310, sellPrice: 290 },
      { goodId: 'agri', buyPrice: 85, sellPrice: 75 },
      { goodId: 'info', buyPrice: 620, sellPrice: 580 },
      { goodId: 'parts', buyPrice: 410, sellPrice: 390 },
      { goodId: 'artifacts', buyPrice: 2100, sellPrice: 1900 },
    ],
  },
  {
    id: 'aqua',
    name: 'Aqua Ventus',
    position: { x: 150, y: 450, z: -30 },
    taxRate: 0.02,
    description: "An ocean world, rich in water resources but desperate for advanced technology and minerals.",
    color: 'aquamarine',
    market: [
      { goodId: 'water', buyPrice: 15, sellPrice: 10 },
      { goodId: 'food', buyPrice: 60, sellPrice: 50 },
      { goodId: 'minerals', buyPrice: 180, sellPrice: 160 },
      { goodId: 'tech', buyPrice: 550, sellPrice: 520 },
      { goodId: 'meds', buyPrice: 280, sellPrice: 260 },
      { goodId: 'robots', buyPrice: 900, sellPrice: 850 },
      { goodId: 'luxuries', buyPrice: 1300, sellPrice: 1200 },
      { goodId: 'gases', buyPrice: 350, sellPrice: 320 },
      { goodId: 'agri', buyPrice: 70, sellPrice: 60 },
      { goodId: 'info', buyPrice: 680, sellPrice: 640 },
      { goodId: 'parts', buyPrice: 480, sellPrice: 450 },
      { goodId: 'artifacts', buyPrice: 2500, sellPrice: 2200 },
    ],
  },
  {
    id: 'volcanis',
    name: 'Volcanis',
    position: { x: 650, y: 150, z: 50 },
    taxRate: 0.1,
    description: 'A mineral-rich volcanic planet. The harsh environment makes food and water scarce and valuable.',
    color: 'orangered',
    market: [
      { goodId: 'water', buyPrice: 35, sellPrice: 30 },
      { goodId: 'food', buyPrice: 70, sellPrice: 60 },
      { goodId: 'minerals', buyPrice: 120, sellPrice: 100 },
      { goodId: 'tech', buyPrice: 520, sellPrice: 490 },
      { goodId: 'meds', buyPrice: 300, sellPrice: 280 },
      { goodId: 'robots', buyPrice: 850, sellPrice: 820 },
      { goodId: 'luxuries', buyPrice: 1400, sellPrice: 1300 },
      { goodId: 'gases', buyPrice: 250, sellPrice: 220 },
      { goodId: 'agri', buyPrice: 100, sellPrice: 90 },
      { goodId: 'info', buyPrice: 700, sellPrice: 650 },
      { goodId: 'parts', buyPrice: 450, sellPrice: 420 },
      { goodId: 'artifacts', buyPrice: 1800, sellPrice: 1600 },
    ],
  },
  {
    id: 'xylos',
    name: 'Xylos',
    position: { x: 100, y: 100, z: 10 },
    taxRate: 0.03,
    description: "A lush jungle world teeming with exotic flora and fauna. Its primary export is nutrient-rich food paste.",
    color: 'forestgreen',
    market: [
      { goodId: 'water', buyPrice: 25, sellPrice: 20 },
      { goodId: 'food', buyPrice: 30, sellPrice: 25 },
      { goodId: 'minerals', buyPrice: 160, sellPrice: 150 },
      { goodId: 'tech', buyPrice: 600, sellPrice: 550 },
      { goodId: 'meds', buyPrice: 240, sellPrice: 220 },
      { goodId: 'robots', buyPrice: 950, sellPrice: 900 },
      { goodId: 'luxuries', buyPrice: 1000, sellPrice: 900 },
      { goodId: 'gases', buyPrice: 330, sellPrice: 310 },
      { goodId: 'agri', buyPrice: 60, sellPrice: 50 },
      { goodId: 'info', buyPrice: 720, sellPrice: 680 },
      { goodId: 'parts', buyPrice: 500, sellPrice: 470 },
      { goodId: 'artifacts', buyPrice: 2300, sellPrice: 2100 },
    ],
  },
  {
    id: 'cygnus',
    name: 'Cygnus X-1',
    position: { x: 200, y: 500, z: -40 },
    taxRate: 0.12,
    description: "A heavily fortified mining outpost orbiting a black hole. Dangerous, but the source of the galaxy's rarest crystals.",
    color: 'darkslateblue',
    market: [
      { goodId: 'water', buyPrice: 40, sellPrice: 35 },
      { goodId: 'food', buyPrice: 80, sellPrice: 75 },
      { goodId: 'minerals', buyPrice: 100, sellPrice: 90 },
      { goodId: 'tech', buyPrice: 530, sellPrice: 500 },
      { goodId: 'meds', buyPrice: 320, sellPrice: 300 },
      { goodId: 'robots', buyPrice: 880, sellPrice: 850 },
      { goodId: 'luxuries', buyPrice: 1500, sellPrice: 1400 },
      { goodId: 'gases', buyPrice: 280, sellPrice: 260 },
      { goodId: 'agri', buyPrice: 110, sellPrice: 100 },
      { goodId: 'info', buyPrice: 750, sellPrice: 700 },
      { goodId: 'parts', buyPrice: 430, sellPrice: 400 },
      { goodId: 'artifacts', buyPrice: 1500, sellPrice: 1300 },
    ],
  },
  {
    id: 'new-eden',
    name: 'New Eden',
    position: { x: 500, y: 500, z: 0 },
    taxRate: 0.15,
    description: "A perfectly terraformed paradise, home to the galaxy's elite. Luxury goods fetch a high price, but taxes are steep.",
    color: 'gold',
    market: [
      { goodId: 'water', buyPrice: 25, sellPrice: 20 },
      { goodId: 'food', buyPrice: 60, sellPrice: 55 },
      { goodId: 'minerals', buyPrice: 170, sellPrice: 160 },
      { goodId: 'tech', buyPrice: 500, sellPrice: 480 },
      { goodId: 'meds', buyPrice: 220, sellPrice: 200 },
      { goodId: 'robots', buyPrice: 780, sellPrice: 750 },
      { goodId: 'luxuries', buyPrice: 1800, sellPrice: 1600 },
      { goodId: 'gases', buyPrice: 340, sellPrice: 320 },
      { goodId: 'agri', buyPrice: 90, sellPrice: 80 },
      { goodId: 'info', buyPrice: 550, sellPrice: 500 },
      { goodId: 'parts', buyPrice: 460, sellPrice: 430 },
      { goodId: 'artifacts', buyPrice: 3000, sellPrice: 2700 },
    ],
  },
  {
    id: 'helion',
    name: 'Helion',
    position: { x: 700, y: 400, z: 25 },
    taxRate: 0.04,
    description: "A scorching desert world where colossal solar arrays harvest energy for high-tech manufacturing. Water is more valuable than gold.",
    color: 'sandybrown',
    market: [
      { goodId: 'water', buyPrice: 50, sellPrice: 45 },
      { goodId: 'food', buyPrice: 75, sellPrice: 65 },
      { goodId: 'minerals', buyPrice: 160, sellPrice: 150 },
      { goodId: 'tech', buyPrice: 450, sellPrice: 420 },
      { goodId: 'meds', buyPrice: 290, sellPrice: 270 },
      { goodId: 'robots', buyPrice: 750, sellPrice: 720 },
      { goodId: 'luxuries', buyPrice: 1450, sellPrice: 1350 },
      { goodId: 'gases', buyPrice: 280, sellPrice: 250 },
      { goodId: 'agri', buyPrice: 120, sellPrice: 110 },
      { goodId: 'info', buyPrice: 650, sellPrice: 600 },
      { goodId: 'parts', buyPrice: 380, sellPrice: 350 },
      { goodId: 'artifacts', buyPrice: 2200, sellPrice: 2000 },
    ],
  },
  {
    id: 'krystallos',
    name: 'Krystallos',
    position: { x: 50, y: 250, z: -15 },
    taxRate: 0.03,
    description: "A frozen wasteland of towering ice spires. The planet's sole export is cryo-distilled Aqua Pura.",
    color: 'lightcyan',
    market: [
      { goodId: 'water', buyPrice: 12, sellPrice: 8 },
      { goodId: 'food', buyPrice: 65, sellPrice: 55 },
      { goodId: 'minerals', buyPrice: 190, sellPrice: 170 },
      { goodId: 'tech', buyPrice: 580, sellPrice: 540 },
      { goodId: 'meds', buyPrice: 270, sellPrice: 250 },
      { goodId: 'robots', buyPrice: 920, sellPrice: 880 },
      { goodId: 'luxuries', buyPrice: 1350, sellPrice: 1250 },
      { goodId: 'gases', buyPrice: 300, sellPrice: 270 },
      { goodId: 'agri', buyPrice: 95, sellPrice: 85 },
      { goodId: 'info', buyPrice: 690, sellPrice: 650 },
      { goodId: 'parts', buyPrice: 490, sellPrice: 460 },
      { goodId: 'artifacts', buyPrice: 2400, sellPrice: 2150 },
    ],
  },
  {
    id: 'mechanos',
    name: 'Mechanos',
    position: { x: 300, y: 50, z: 45 },
    taxRate: 0.08,
    description: "A planet-sized city of chrome and circuits. The inhabitants are masters of technology but require constant imports of raw materials.",
    color: 'slategray',
    market: [
      { goodId: 'water', buyPrice: 30, sellPrice: 25 },
      { goodId: 'food', buyPrice: 60, sellPrice: 55 },
      { goodId: 'minerals', buyPrice: 200, sellPrice: 180 },
      { goodId: 'tech', buyPrice: 430, sellPrice: 400 },
      { goodId: 'meds', buyPrice: 260, sellPrice: 240 },
      { goodId: 'robots', buyPrice: 700, sellPrice: 650 },
      { goodId: 'luxuries', buyPrice: 1600, sellPrice: 1500 },
      { goodId: 'gases', buyPrice: 320, sellPrice: 300 },
      { goodId: 'agri', buyPrice: 105, sellPrice: 95 },
      { goodId: 'info', buyPrice: 500, sellPrice: 450 },
      { goodId: 'parts', buyPrice: 350, sellPrice: 320 },
      { goodId: 'artifacts', buyPrice: 2800, sellPrice: 2500 },
    ],
  },
  {
    id: 'ruin',
    name: 'Ruin',
    position: { x: 750, y: 550, z: -5 },
    taxRate: 0.01,
    description: "The radioactive husk of a forgotten civilization. Risky to visit, but scavengers sometimes unearth valuable Xenon Crystals from the debris.",
    color: 'olive',
    market: [
      { goodId: 'water', buyPrice: 45, sellPrice: 40 },
      { goodId: 'food', buyPrice: 90, sellPrice: 80 },
      { goodId: 'minerals', buyPrice: 110, sellPrice: 95 },
      { goodId: 'tech', buyPrice: 700, sellPrice: 650 },
      { goodId: 'meds', buyPrice: 350, sellPrice: 320 },
      { goodId: 'robots', buyPrice: 1000, sellPrice: 950 },
      { goodId: 'luxuries', buyPrice: 1700, sellPrice: 1600 },
      { goodId: 'gases', buyPrice: 400, sellPrice: 370 },
      { goodId: 'agri', buyPrice: 130, sellPrice: 120 },
      { goodId: 'info', buyPrice: 800, sellPrice: 750 },
      { goodId: 'parts', buyPrice: 550, sellPrice: 500 },
      { goodId: 'artifacts', buyPrice: 1200, sellPrice: 1000 },
    ],
  },
];

const GALAXY: Galaxy = {
  name: 'MakeMoney',
  planets: PLANETS,
  goods: GOODS,
};

const INITIAL_PLAYER_STATE: PlayerState = {
  credits: 1000,
  currentPlanetId: 'terra',
  isTraveling: false,
  travelInfo: null,
  ship: {
    name: 'Stardust Cruiser',
    durability: 100,
    maxDurability: 100,
    cargo: {
      capacity: 20,
      items: [],
    },
    upgrades: {
      cargo: 1,
      durability: 1,
    },
  },
};

export const INITIAL_GAME_STATE: GameState = {
  player: INITIAL_PLAYER_STATE,
  galaxy: GALAXY,
  lastUpdated: new Date().toISOString(),
  checksum: '',
};

export const SHIP_SPEED = 100; // units per second
export const MARKET_UPDATE_INTERVAL = 10000; // 10 seconds
export const AUTOSAVE_INTERVAL = 5 * 60 * 1000; // 5 minutes
export const SAVE_GAME_KEY = 'galaxyTraderState';